<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head profile="http://purl.org/uF/2008/03/">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>Newswise</title>
   
    <!--[if IE]>
		<link rel="stylesheet" type="text/css" href="/stylesheets/popup-ie.css"  />
	<![endif]-->
	<!--[if IE 6]>
		<link rel="stylesheet" type="text/css" href="/stylesheets/popup-ie6.css"  />
	<![endif]-->
</head>
<body>
	<?= $this->layout()->content ?>	
</body>
</html>